# Generated by Django 4.2.2 on 2023-06-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="trash",
            field=models.BooleanField(default=False),
        ),
    ]
